// DB Flags
exports.OBJECT_DUPLICATE = 'OBJECT_DUPLICATE';
exports.OBJECT_NOT_FOUND = 'OBJECT_NOT_FOUND';

// Token Flags
exports.TOKEN_EXPIRED = 'TOKEN_EXPIRED';
exports.TOKEN_MALFORMED = 'TOKEN_MALFORMED';

// Permissions Flags
exports.ACCESS_DENIED = 'ACCESS_DENIED';
exports.UNAUTHORIZED = 'UNAUTHORIZED';

// Query Flags
exports.QUERY_DEPTH_EXCEEDED = 'QUERY_DEPTH_EXCEEDED';
exports.QUERY_COMPLEXITY_EXCEEDED = 'QUERY_COMPLEXITY_EXCEEDED';
exports.QUERY_BREADTH_EXCEEDED = 'QUERY_BREADTH_EXCEEDED';

// Mystery Flags
exports.UNKNOWN_ERROR = 'UKNOWN_ERROR';
